#!/usr/bin/env python3
"""Tests for the Hermes-ported core/tts.py, core/vision.py, core/imagine.py.

Hermetic pattern: ATROPOS_HOME → tempdir, urllib mocked via
mock.patch("urllib.request.urlopen") — no network, no real binaries
(edge-tts/piper/neutts are never on PATH in tests; providers report
unavailable and the chain degrades gracefully).
"""
import json
import os
import shutil
import struct
import sys
import tempfile
import unittest
from pathlib import Path
from unittest import mock

_REPO = Path(__file__).resolve().parent.parent
if str(_REPO) not in sys.path:
    sys.path.insert(0, str(_REPO))

from core import imagine, tts, vision  # noqa: E402

# 2x1 RGB PNG for the stdlib codec + dimension probe. Generated by the
# codec itself (encode_png) so the fixture is guaranteed valid, and zlib-
# exact unlike a hand-assembled hex blob.
def _make_fixture_png():
    row = b"\xff\x00\x00" + b"\x00\xff\x00"  # red, green
    return vision.encode_png(2, 1, [row])


_ONE_PX_PNG = _make_fixture_png()

# Minimal WAV (44-byte RIFF header + 100 silent samples) for Ogg repair tests.
def _wav_bytes():
    sample_rate = 24000
    channels, width = 1, 2
    data = b"\x00\x00" * 100
    byte_rate = sample_rate * channels * width
    block_align = channels * width
    fmt = struct.pack("<4sIHHIIHH", b"fmt ", 16, 1, channels, sample_rate,
                      byte_rate, block_align, width * 8)
    return (b"RIFF" + struct.pack("<I", 4 + len(fmt) + 8 + len(data)) + b"WAVE"
            + fmt + b"data" + struct.pack("<I", len(data)) + data)


class TtsTests(unittest.TestCase):
    """core/tts.py — provider chain, normalize port, voice list shape."""

    def setUp(self):
        self._a = os.environ.get("ATROPOS_HOME")
        self.tmp = tempfile.mkdtemp(prefix="atropos_tts_")
        os.environ["ATROPOS_HOME"] = self.tmp
        os.environ.pop("NINEROUTER_URL", None)
        os.environ.pop("NINEROUTER_KEY", None)
        os.environ.pop("OPENAI_API_KEY", None)
        os.environ.pop("ELEVENLABS_API_KEY", None)
        os.environ.pop("GEMINI_API_KEY", None)
        os.environ.pop("GOOGLE_API_KEY", None)
        for name in ("edge-tts", "edge-tts.bat", "piper", "neutts", "ffmpeg"):
            self.addCleanup(self._restore_which, name)
        self._which_orig = {}
        for name in ("edge-tts", "edge-tts.bat", "piper", "neutts", "ffmpeg"):
            self._which_orig[name] = shutil.which(name)
        # Force every binary provider to look unavailable.
        self._which_patcher = mock.patch.object(shutil, "which",
                                                side_effect=lambda c: None)
        self._which_patcher.start()

    def tearDown(self):
        self._which_patcher.stop()
        if self._a is not None:
            os.environ["ATROPOS_HOME"] = self._a
        else:
            os.environ.pop("ATROPOS_HOME", None)
        shutil.rmtree(self.tmp, ignore_errors=True)

    def _restore_which(self, name):
        pass

    def test_gateway_unavailable_chain_falls_through_to_clean_failure(self):
        # No gateway env, no API keys, no binaries: auto chain must
        # resolve to a graceful {ok:False, error} — never a crash.
        res = tts.tts("hello world")
        self.assertIsInstance(res, dict)
        self.assertFalse(res.get("ok"))
        self.assertTrue(res.get("error"))

    def test_gateway_first_when_configured(self):
        # Gateway is the FIRST provider in the chain: with env set and
        # urlopen mocked to succeed, tts must return the gateway result
        # without touching local providers.
        os.environ["NINEROUTER_URL"] = "https://gw.example"
        os.environ["NINEROUTER_KEY"] = "k"
        with mock.patch("urllib.request.urlopen") as mu:
            mu.return_value.__enter__.return_value.read.return_value = json.dumps(
                {"ok": True, "url": "https://gw.example/a.mp3"}).encode()
            res = tts.tts("hello")
        self.assertTrue(res.get("ok"))
        self.assertEqual(res.get("provider"), "gateway")
        req = mu.call_args.args[0]
        self.assertEqual(req.full_url, "https://gw.example/v1/tts")
        body = json.loads(req.data.decode())
        self.assertEqual(body["text"], "hello")

    def test_explicit_provider_unconfigured_returns_clean_error(self):
        # provider="openai" with no key: {ok:False, error}, no crash.
        res = tts.tts("hello", provider="openai")
        self.assertFalse(res.get("ok"))
        self.assertIn("OPENAI_API_KEY", res.get("error", ""))

    def test_voice_list_shape(self):
        res = tts.list_voices()
        self.assertTrue(res.get("ok"))
        voices = res["voices"]
        self.assertIsInstance(voices, list)
        self.assertGreater(len(voices), 20)
        self.assertTrue(voices[0]["provider"])
        self.assertTrue(voices[0]["name"])
        self.assertIn("default", voices[0])
        # the Hermes default edge voice is flagged default
        defaults = [v for v in voices if v["provider"] == "edge" and v["default"]]
        self.assertTrue(defaults)

    def test_prepare_spoken_text_markdown(self):
        src = "**Bold** and *italic* and `code` and [link](https://x.example)"
        out = tts.prepare_spoken_text(src, max_chars=None)
        self.assertNotIn("**", out)
        self.assertNotIn("[link]", out)
        self.assertNotIn("```", out)
        self.assertIn("Bold", out)

    def test_prepare_spoken_text_symbols(self):
        out = tts.prepare_spoken_text("It is 21°C and 5 km/h", max_chars=None)
        self.assertIn("21 degrees Celsius", out)
        self.assertIn("kilometres per hour", out)
        out2 = tts.prepare_spoken_text("Save $50 & buy 20%", max_chars=None)
        self.assertIn("50 dollars", out2)
        self.assertIn(" and ", out2)
        self.assertIn("percent", out2)

    def test_prepare_spoken_text_think_block_stripped(self):
        src = "Hello <think>internal reasoning</think> world"
        out = tts.prepare_spoken_text(src, max_chars=None)
        self.assertNotIn("internal reasoning", out)
        self.assertIn("Hello", out)
        self.assertIn("world", out)

    def test_max_text_length_truncates(self):
        res = tts._resolve_max_text_length("openai")
        self.assertEqual(res, 4096)
        res = tts._resolve_max_text_length("gemini")
        self.assertEqual(res, 32000)
        res = tts._resolve_max_text_length("unknown-provider")
        self.assertEqual(res, tts.FALLBACK_MAX_TEXT_LENGTH)

    def test_sentence_chunker(self):
        ch = tts.SentenceChunker(min_len=10)
        sents = ch.feed("First sentence. Second one.")
        self.assertEqual(len(sents), 2)
        self.assertEqual(ch.flush(), [])

    def test_wrap_pcm_as_wav_and_sniff(self):
        pcm = b"\x00\x00" * 100
        wav = tts._wrap_pcm_as_wav(pcm)
        self.assertEqual(wav[:4], b"RIFF")
        self.assertEqual(tts.sniff_container(wav), "wav")
        self.assertEqual(tts.sniff_container(b"OggS" + b"\x00" * 8), "ogg")
        self.assertEqual(tts.sniff_container(b"ID3" + b"\x00" * 8), "mp3")
        self.assertEqual(tts.sniff_container(b"\xff\xfb" + b"\x00" * 10), "mp3")
        self.assertIsNone(tts.sniff_container(b"not audio at all"))

    def test_repair_ogg_renames_mislabeled_wav(self):
        # WAV bytes in a .ogg path (ffmpeg absent in tests) → renamed to
        # the honest .wav extension (Hermes _repair_ogg_container fallback).
        p = Path(self.tmp) / "voice.ogg"
        p.write_bytes(_wav_bytes())
        repaired = tts._repair_ogg_container(str(p))
        self.assertTrue(repaired.endswith(".wav"))
        self.assertTrue(Path(repaired).exists())

    def test_edge_missing_binary_stage_note(self):
        res = tts._stage_unavailable("edge")
        self.assertFalse(res["ok"])
        self.assertIn("edge-tts", res["error"])


class VisionTests(unittest.TestCase):
    """core/vision.py — missing file, gateway payload, pure resize steps."""

    def setUp(self):
        self._a = os.environ.get("ATROPOS_HOME")
        self.tmp = tempfile.mkdtemp(prefix="atropos_vision_")
        os.environ["ATROPOS_HOME"] = self.tmp
        os.environ.pop("NINEROUTER_URL", None)
        os.environ.pop("NINEROUTER_KEY", None)
        self.png = Path(self.tmp) / "img.png"
        self.png.write_bytes(_ONE_PX_PNG)

    def tearDown(self):
        if self._a is not None:
            os.environ["ATROPOS_HOME"] = self._a
        else:
            os.environ.pop("ATROPOS_HOME", None)
        shutil.rmtree(self.tmp, ignore_errors=True)

    def test_missing_file_graceful(self):
        res = vision.analyze(str(Path(self.tmp) / "nope.png"))
        self.assertIsInstance(res, dict)
        self.assertFalse(res.get("ok"))
        self.assertIn("not found", res.get("error", ""))

    def test_gateway_called_first_with_right_payload(self):
        os.environ["NINEROUTER_URL"] = "https://gw.example"
        os.environ["NINEROUTER_KEY"] = "k"
        with mock.patch("urllib.request.urlopen") as mu:
            mu.return_value.__enter__.return_value.read.return_value = json.dumps(
                {"success": True, "analysis": "a red apple"}).encode()
            res = vision.analyze(str(self.png), prompt="What is this?")
        self.assertTrue(res.get("ok"))
        self.assertEqual(res.get("provider"), "gateway")
        self.assertEqual(res.get("description"), "a red apple")
        req = mu.call_args.args[0]
        self.assertEqual(req.full_url, "https://gw.example/v1/vision")
        body = json.loads(req.data.decode())
        self.assertEqual(body["prompt"], "What is this?")
        self.assertTrue(Path(body["image_path"]).exists())

    def test_gateway_error_falls_to_local_provider(self):
        # Gateway env unset → local provider attempted; no API key →
        # clean {ok:False, error}.
        res = vision.analyze(str(self.png))
        self.assertFalse(res.get("ok"))
        self.assertTrue(res.get("error"))

    def test_downscale_ordering_pure(self):
        # Hermes ordering: halve the longer side and scale the shorter
        # side proportionally (min dimension 64), stop once the dimension
        # budget is satisfied, nd never grow.
        # dims within the max_dimension budget → no resize.
        self.assertEqual(vision._resize_dimension_steps(2000, 1000, max_dimension=7900), [])
        # over the budget → halving schedule until within budget.
        steps = vision._resize_dimension_steps(2000, 1000, max_dimension=1024)
        self.assertEqual(steps[0], (1000, 500))
        self.assertEqual(len(steps), 1)  # stops as soon as the budget fits
        steps2 = vision._resize_dimension_steps(2000, 1000, max_dimension=512)
        self.assertEqual(steps2, [(1000, 500), (500, 250)])
        # byte-path mode (no max_dimension): halve down to the 64 floor.
        steps3 = vision._resize_dimension_steps(200, 150)
        self.assertEqual(steps3, [(100, 75), (64, 64)])
        for (w, h) in steps3:
            self.assertGreaterEqual(w, 64)
            self.assertGreaterEqual(h, 64)
        # _allow_byte_path=False short-circuits the byte mode (the byte
        # budget judge said no shrink needed).
        self.assertEqual(vision._resize_dimension_steps(2000, 1000, max_dimension=None,
                                                        _allow_byte_path=False), [])

    def test_quality_steps(self):
        self.assertEqual(vision._resize_quality_steps("JPEG"), (85, 70, 50))
        self.assertEqual(vision._resize_quality_steps("PNG"), (None,))

    def test_image_dimensions_header_probe(self):
        dims = vision._image_dimensions(self.png)
        self.assertEqual(dims, (2, 1))

    def test_png_codec_roundtrip(self):
        w, h, rows = vision.decode_image(self.png)
        self.assertEqual((w, h), (2, 1))
        out = vision.encode_png(w, h, rows)
        copy = Path(self.tmp) / "copy.png"
        copy.write_bytes(out)
        w2, h2, rows2 = vision.decode_image(copy)
        self.assertEqual((w2, h2), (2, 1))
        self.assertEqual(rows2[0], rows[0])
        self.assertTrue(out.startswith(b"\x89PNG"))

    def test_jpeg_dimension_parse(self):
        # Minimal JPEG SOF0 scan: ff d8 ... ff c0 00 11 08 00 64 00 c8 ...
        jpg = (b"\xff\xd8\xff\xe0\x00\x10JFIF\x00\x01\x01\x00\x00\x01\x00\x01\x00\x00"
               b"\xff\xc0\x00\x11\x08\x00\x64\x00\xc8\x03\x01\x22\x00\x02\x11\x01\x03\x11\x01"
               b"\xff\xda")
        dims = vision._image_dimensions(Path(self.tmp) / "t.jpg") if False else None
        # write the bytes and probe through the header parser
        p = Path(self.tmp) / "t.jpg"
        p.write_bytes(jpg)
        dims = vision._image_dimensions(p)
        self.assertEqual(dims, (200, 100))  # height=0x64(100), width=0xc8(200)

    def test_mime_detect(self):
        self.assertEqual(vision._determine_mime_type(self.png), "image/png")
        self.assertEqual(vision._detect_image_mime_type_from_bytes(_ONE_PX_PNG), "image/png")
        self.assertIsNone(vision._detect_image_mime_type_from_bytes(b"<svg></svg>"))


class ImagineTests(unittest.TestCase):
    """core/imagine.py — payload shape, graceful missing-provider path."""

    def setUp(self):
        self._a = os.environ.get("ATROPOS_HOME")
        self.tmp = tempfile.mkdtemp(prefix="atropos_imagine_")
        os.environ["ATROPOS_HOME"] = self.tmp
        os.environ.pop("NINEROUTER_URL", None)
        os.environ.pop("NINEROUTER_KEY", None)
        os.environ.pop("FAL_KEY", None)
        os.environ.pop("FAL_API_KEY", None)

    def tearDown(self):
        if self._a is not None:
            os.environ["ATROPOS_HOME"] = self._a
        else:
            os.environ.pop("ATROPOS_HOME", None)
        shutil.rmtree(self.tmp, ignore_errors=True)

    def test_missing_prompt_graceful(self):
        res = imagine.generate("")
        self.assertFalse(res.get("ok"))
        self.assertIn("Prompt is required", res.get("error", ""))

    def test_no_provider_graceful(self):
        # No gateway env, no FAL_KEY → {ok:False, error} without a crash.
        res = imagine.generate("a red fox")
        self.assertFalse(res.get("ok"))
        self.assertTrue(res.get("error"))
        self.assertIn("FAL_KEY", res.get("error", ""))

    def test_gateway_first_with_payload(self):
        os.environ["NINEROUTER_URL"] = "https://gw.example"
        os.environ["NINEROUTER_KEY"] = "k"
        with mock.patch("urllib.request.urlopen") as mu:
            mu.return_value.__enter__.return_value.read.return_value = json.dumps(
                {"url": "https://gw.example/img.png", "model": "flux"}).encode()
            res = imagine.generate("a red fox")
        self.assertTrue(res.get("ok"))
        self.assertEqual(res.get("provider"), "gateway")
        req = mu.call_args.args[0]
        self.assertEqual(req.full_url, "https://gw.example/v1/images/generations")
        body = json.loads(req.data.decode())
        self.assertEqual(body["prompt"], "a red fox")

    def test_payload_shape_with_upscale_and_outpaint(self):
        # Gateway path with upscale/outpaint → extended payload passes
        # through (flux3 submit-args contract: arguments minus Nones).
        os.environ["NINEROUTER_URL"] = "https://gw.example"
        os.environ["NINEROUTER_KEY"] = "k"
        with mock.patch("urllib.request.urlopen") as mu:
            mu.return_value.__enter__.return_value.read.return_value = json.dumps(
                {"url": "https://gw.example/b.png"}).encode()
            res = imagine.generate("a castle", size="1024x1024",
                                   upscale=True, outpaint="sky")
        self.assertTrue(res.get("ok"))
        body = json.loads(mu.call_args.args[0].data.decode())
        self.assertEqual(body["prompt"], "a castle")
        self.assertEqual(body["size"], "1024x1024")
        self.assertIs(body["upscale"], True)
        self.assertEqual(body["outpaint"], "sky")

    def test_fal_payload_build_size_translation(self):
        # image_size_preset model: 1024x1024 → square_hd under image_size.
        payload = imagine._build_fal_payload("fal-ai/flux-2/klein/9b", "x", "1024x1024")
        self.assertEqual(payload["image_size"], "square_hd")
        self.assertEqual(payload["prompt"], "x")
        # supports whitelist filters unknown overrides.
        payload2 = imagine._build_fal_payload("fal-ai/flux-2/klein/9b", "x", "800x600",
                                              overrides={"bogus_key": 1})
        self.assertNotIn("bogus_key", payload2)
        # aspect_ratio model family.
        payload3 = imagine._build_fal_payload("fal-ai/nano-banana-pro", "x", "1024x1024")
        self.assertEqual(payload3["aspect_ratio"], "1:1")
        # gpt_literal family.
        payload4 = imagine._build_fal_payload("fal-ai/gpt-image-1.5", "x", "1536x1024")
        self.assertEqual(payload4["image_size"], "1536x1024")

    def test_unknown_model_falls_back_to_default(self):
        model_id, meta = imagine._resolve_fal_model("no/such-model")
        self.assertEqual(model_id, imagine.DEFAULT_MODEL)
        model_id2, _ = imagine._resolve_fal_model()
        self.assertEqual(model_id2, imagine.DEFAULT_MODEL)

    def test_outpaint_expands_preset(self):
        key, value = imagine._size_to_fal("fal-ai/flux-2/klein/9b", "1024x1024", outpaint="yes")
        self.assertEqual(value, "landscape_16_9")
        key2, value2 = imagine._size_to_fal("fal-ai/flux-2/klein/9b", "1536x1024")
        self.assertEqual(value2, "landscape_16_9")


if __name__ == "__main__":
    unittest.main()
